name: Mirror to gitee Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_GITHUB }}
        with:
          source-repo: "git@github.com:sean-lgt/sync-gitee-repo-test.git"
          destination-repo: "git@gitee.com:seantao5/sync-gitee-repo-test.git"